[build]
  builder = "NIXPACKS"

[deploy]
  startCommand = "uvicorn main:app --host 0.0.0.0 --port $PORT"
  healthcheckPath = "/docs"
  restartPolicyType = "ON_FAILURE"

[variables]
  STRIPE_SUCCESS_URL = "https://www.courtcollab.com"
  STRIPE_CANCEL_URL  = "https://www.courtcollab.com"
